:author: Clifton L. McLellan
:email: <clifton@clmsoft.com>
:revdate: 2021-01-31
:encoding: utf-8
:lang: en
:keywords: sunriise, jackcess, jackcess-encrypt, ofx, msmoney
// configuration settings
// ifdef::env-browser[:outfilesuffix: .adoc]
ifndef::env-github,env-gitlab[:icons: font]
ifdef::env-github,env-gitlab[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// variables
:workdir: ~/work
:svnrepo: svn://svn.code.sf.net/p/sunriise/code
:usersfilename: sunriise_users.txt
:userslist: {workdir}/{usersfilename}
:branchname: Java11_build_updates

== Importing this project from SourceForge to GitHub

Goals:

. Import (fork) the code from the SourceForge
  https://sourceforge.net/projects/sunriise/[Sunriise]
  project, creating a repo on GitHub.

. Update the GitHub repo to more recent versions of development tools.

Technically, those are only the goals for this project.
My goal in getting this project running with later tools is to have a
known tested project where I can play with implementing the
new APIs and functionality of the newly released (as of January 2021)
4.0.0 releases of
https://jackcess.sourceforge.io[Jackcess]
and
https://jackcessencrypt.sourceforge.io[Jackcess Encrypt]
for working with data from my old
password-protected, encrypted
MS Money files on Mac / Linux.

This document describes how I imported (forked) this project from its old
(2011 - 2013) SourceForge svn repository
into this current GitHub git repository, and the steps I took to get it
to compile and get all the tests running on Java 11 in 2021.

=== Get a list of committers from the original project

Check out a current copy of the SourceForge svn repo and create a file containing
all the users who have previously committed to the
repo in the format for usernames / emails used by git:

[source,bash,subs="attributes"]
----
mkdir {workdir}
cd {workdir}
svn checkout {svnrepo} sunriise-svn
cd sunriise-svn
svn log --xml --quiet | grep author | sort -u | perl -pe 's/.*>(.*?)<.*/$1 = /' > {userslist}
----

The resulting file should look something like:

.{usersfilename} (before editing)
----
hle999 =
hleofxquotes =
----

These users and their email addresses exist within the source code
(for example, in the pom.xml file) so using the info available,
edit the `{userslist}` file to create names and email addresses
corresponding with each svn committer found in the file.
The final file should look something like:

.{usersfilename}
----
hle999       = hle999 <hle999@gmail.com>
hleofxquotes = hleofxquotes <hleofxquotes@gmail.com>
----

=== Convert the repo

There are a couple of ways to convert Subversion repos into git.
Each has its use depending on the complexity of the repo. Use
one of these methods, or try them both and compare the result.

NOTE: The SourceForge svn repo includes directories containing
      libraries with required code modifications used by this
      project.
      Testing of areas I am interested in show that I can
      exclude these modifications by using later release
      versions of these libraries, so the commands below
      exclude them from being imported into this new repository.

==== Convert using `git svn`

[source,bash,subs="attributes"]
----
cd {workdir}

git svn clone {svnrepo} --stdlayout --no-metadata --authors-file {userslist} --ignore-paths '^(?:trunk[/]|tags[/][^/]+[/])(?:jackcess*|sunriise-spring*)' sunriise-gitsvn
----

==== Alternative: Convert using ruby `svn2git` tool

Some repos may have more complex structures with difficult-to-create
regular expressions for including and excluding directories.
For these it might be easier to use the
ruby gem `svn2git`.

NOTE: `svn2git` checks out the remote into the current directory instead of creating
      a new subdirectory, so the second argument above (the directory name to create)
      is not used. We create a new directory manually instead.

With `svn2git` we can import the repository into git as follows:

[source,bash,subs="attributes"]
----
# if ruby bundler is not yet installed you should install it, perhaps by:
# sudo gem install bundler

cd {workdir}
mkdir sunriise-svn2git/
cd    sunriise-svn2git/

bundle init
bundle config set --local path 'vendor/bundle'
bundle add svn2git
bundle install

bundle exec svn2git {svnrepo} --nobranches --exclude 'jackcess*' --exclude 'sunriise-spring*' --authors {userslist} --verbose
----

=== Clean up the converted repo

For my git repository I like to clean up the detritus left over from the conversion.
There are many ways to do this, but my simple method is to perform a `git clone` of
the newly-minted git repo into another pristine copy. Here I use the repo I created
using `git svn` as a source and a new "clean" directory as my target:

[source,bash,subs="attributes"]
----
cd {workdir}
git clone sunriise-gitsvn sunriise-clean
----

I like to diff the source directory trees from the imported versions against the final
"clean" version just to be sure we didn't miss anything. Here I test the clean version
against both imports, ignoring the .git subdirectories which we know to be different:

[source,bash,subs="attributes"]
----
cd {workdir}

diff -rq --exclude '.git' sunriise-clean/ sunriise-gitsvn/
diff -rq --exclude '.git' sunriise-clean/ sunriise-svn2git/
----

In both cases I see that there are two directories missing from the final "clean" repo:

----
src/main/java/com/le/sunriise/model/converter
src/test/data/dict/dir03
----

When we look inside the checked out repos we see both of these directories are empty.
I consider this a positive result of the cleanup process.

== Create a new repository in GitHub

Use the GitHub web site to add a new repository. When that is complete it
displays the URL to the new location.

NOTE: With GitLab I do this from the command line.
      I have not figured out the right incantation
      to do this with GitHub ... yet.

Using this new location, add the contents of the checkout to the new repo in GitHub:

[source,bash,subs="attributes"]
----
cd {workdir}
cd sunriise-clean

# remove the old origin and replace it with the new repo URL
git remote rm origin
git remote add origin git@github.com:clmsoft/sunriise
git push --set-upstream origin master
----

Now check out the repo in a new location to make sure you have exactly what is
in GitHub, and make the changes needed.

[source,bash,subs="attributes"]
----
cd {workdir}

git clone git@github.com:clmsoft/sunriise
----

=== Create a new branch {branchname}

[source,bash,subs="attributes"]
----
cd {workdir}
cd sunriise

git checkout -b {branchname}
----

In the new branch, modify pom.xml with the following minimal changes:

*Upgrade maven pom.xml to work with Java 11.*

Specifically:

* Upgrade maven-compiler-plugin from 2.3.2 to 3.8.0 and change Java version from 1.6 to 9;

* Upgrade the aspectj-maven-plugin from org.codehaus.mojo version 1.3.1 to com.nickwongdev version 1.12.6 (supporting Java 11+) and change its Java compliance version from 1.6 to 1.9;

* Upgrade jackcess-encrypt from 1.0.4-SNAPSHOT to 1.0.4 (Production release, not internally modified version)

* Upgrade jackcess from 1.2.9-SNAPSHOT to 1.2.14.3 (Production release, not internally modified version).


NOTE: I was also tempted to add the default
      Maven Central Repository
      since the configured repos did not have as large a selection
      of available versions, but I found versions that worked and
      existed in the configured repos.

If needed in the future, the Maven Central Repository can be added as

[source,xml]
----
<repository>
    <id>repo1.maven.org</id>
    <name>Maven Central Repository</name>
    <url>https://repo1.maven.org/maven2/</url>
    <layout>default</layout>
</repository>
----

=== Merge the branch into master

When all the changes are completed on the working branch and all tests are
green, commit your changes on the branch, (optionally) push it upstream,
then checkout the main branch and merge the working branch back in.

[source, bash]
----
git branch --set-upstream-to=origin/{branchname} {branchname}

git checkout master
git fetch
git pull
git merge {branchname}
----
