/*******************************************************************************
 * Copyright (c) 2012 Hung Le
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *******************************************************************************/
package com.le.sunriise.rc4;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/openssl/rc4.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RC4_KEY extends Structure {
	public byte x;
	public byte y;
	/// C type : unsigned char[256]
	public byte[] data = new byte[256];
	public RC4_KEY() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"x", "y", "data"});
	}
	/// @param data C type : unsigned char[256]
	public RC4_KEY(byte x, byte y, byte data[]) {
		super();
		this.x = x;
		this.y = y;
		if (data.length != this.data.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
		initFieldOrder();
	}
	public static class ByReference extends RC4_KEY implements Structure.ByReference {
		
	};
	public static class ByValue extends RC4_KEY implements Structure.ByValue {
		
	};
}
